### ISSUE TITLE
"Not a feed" error when importing Squarespace feed

### ISSUE THREAD

**Issue by spiffytech** [hexojs/hexo-migrator-rss#3]
I'm trying to import my [RSS feed from Squarespace](http://spiffyte.ch/travel-blog?format=RSS) and hexo-migrator-rss finds 0 posts and aborts with "Something's wrong", but no indication what.

I put some logging messages in, and found that the callback on both lines [38](https://github.com/hexojs/hexo-migrator-rss/blob/f2e4aa32f0/index.js#L38) and [40](https://github.com/hexojs/hexo-migrator-rss/blob/f2e4aa32f0/index.js#L40) receive an error parameter of "Error: Not a feed".

(BTW that error is never reported in the console output. Very unhelpful.)

My RSS feed validates, so I'm not sure why the migrator thinks it's not a feed.

**Comment by Xuanwo** [comment]
How about use this specific file http://spiffy.tech/feed.xml ?
Your link is just a html.

**Comment by spiffytech** [comment]
Apologies, my site is no longer on Squarespace, and the RSS link I filed with the ticket no longer points to the Squarespace feed that Hexo had trouble with. And I wasn't clever enough to save a sample of the feed before shutting down my Squarespace account.

Since this can no longer be replicated, I'm closing the ticket.
