### ISSUE TITLE
undefined migrator plugin is not installed

### ISSUE THREAD

**Issue by gabygoole** [hexojs/hexo-migrator-rss#6]
after I do  $ npm install hexo-migrator-rss --save  
I go to my blog file and open git bash ,do $ hexo migrate rss <source>,it prompt  ：
undefined migrator plugin is not installed.  
Installed migrator plugins:

For more help, you can check the online docs: http://hexo.io/  

how to solve that?please!

**Comment by Xuanwo** [comment]
you should do `npm install hexo-migrator-rss --save` in your blog directory

**Comment by gabygoole** [comment]
多谢，看了你的资料才知道你不是歪果仁  
请问你知道如何用RSS的方法把博客园的文章迁移到hexo上吗？  
我找不到我自己博客的RSS，求教！

**Comment by gabygoole** [comment]
执行这条命令npm install hexo-migrator-rss --save 确实可以迁移，但是他只给了我首页的RSS只迁移过来10篇文章

**Comment by Xuanwo** [comment]
http://guochunyang.me/2015/02/08/move-blogs-from-cnblogs-to-jekyll/

参考这篇文章的话，后台应该有一个导出RSS文章备份的功能？

**Comment by gabygoole** [comment]
多谢！
